black-list-worlds:
- Hub
default-language: en
allow-civ-item-sharing: false
explosion-override: false
price-multiplier: 1
item-groups:
  door: WOODEN_DOOR
  glass: GLASS,THIN_GLASS,IRON_FENCE
  furnace: FURNACE,BURNING_FURNACE
  primary: WOOD,SAND,CLAY,PACKED_ICE,WOOL,STONE
  secondary: LOG,LOG_2,SANDSTONE,BRICK,SNOW_BLOCK,SMOOTH_BRICK,COBBLESTONE