black-list-worlds:
- Hub
default-language: en
allow-civ-item-sharing: false
explosion-override: false
use-starter-book: true
price-multiplier: 1
exp-modifier: 0.2
jail-time-seconds: 300
death-grace-period-seconds: 60
points:
  killstreak: 0.1
  killjoy: 0.2
  kill: 1
  death: -1
  half-health: 0.5
  quarter-health: 1
money:
  killstreak: 1
  killjoy: 1
  kill: 1
  death: -1
  karma: 0.1
karma-per-kill: 1
karma-per-kill-streak: 1
folders:
  farms: STONE_HOE
item-groups:
  door: WOODEN_DOOR,ACACIA_DOOR,DARK_OAK_DOOR,SPRUCE_DOOR,BIRCH_DOOR,JUNGLE_DOOR
  glass: GLASS,THIN_GLASS,IRON_FENCE,STAINED_GLASS,STAINED_GLASS_PANE
  furnace: FURNACE,BURNING_FURNACE
  primary: WOOD,SAND,CLAY,PACKED_ICE,WOOL,STONE
  secondary: LOG,LOG_2,SANDSTONE,BRICK,SNOW_BLOCK,SMOOTH_BRICK,COBBLESTONE
groups:
  shop: 3
  quarry: 12