author: Multitallented
database: false
author: Multitallented
description: Allows you to create structures and towns.
main: org.redcastlemedia.multitallented.civs.Civs
name: Civs
startup: postworld
version: 0.0.1-b001
api-version: 1.13
depend: [Vault]
commands:
   cv:
      aliases: ['township', 'townships', 'towns', 'town', 'to', 'hs', 'cv', 'towny', 'fa', 'f', 'faction']
      description: Civs commands
      usage: /<command>
permissions:
   civs.join:
       description: Allows players to join towns
       default: true
   civs.choose:
       description: Allows a player to choose classes
       default: true
   civs.shop:
       description: Allows players to use the shop
       default: true
   civs.admin:
      description: Lets you use admin commands and bypass protections
      default: op
loadafter: [Vault]